# Generated by Django 4.1.3 on 2023-02-23 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Appoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
