# Generated by Django 4.1.3 on 2023-02-24 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appoint', '0003_appointment_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='customer',
            new_name='Name',
        ),
    ]
