# Generated by Django 4.1.3 on 2023-02-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appoint', '0004_rename_customer_appointment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Name',
            field=models.CharField(max_length=20),
        ),
    ]
