# Generated by Django 4.1.3 on 2023-02-24 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appoint', '0009_remove_appointment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Name',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Appoint.user'),
        ),
    ]
