# Generated by Django 4.1.3 on 2023-02-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appoint', '0013_remove_appointment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
