# Generated by Django 4.1.3 on 2023-02-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appoint', '0015_alter_appointment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='UserName',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
