# Generated by Django 4.1.3 on 2023-02-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appoint', '0016_remove_appointment_name_appointment_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='UserName',
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default='alim lalani', max_length=100),
        ),
    ]
