# Generated by Django 4.1.3 on 2023-02-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appoint', '0017_remove_appointment_username_appointment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
