# Generated by Django 4.1.3 on 2023-02-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appoint', '0018_alter_appointment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
