# Generated by Django 4.1.3 on 2023-02-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appoint', '0019_alter_appointment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
