# Generated by Django 4.1.3 on 2023-02-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appoint', '0022_alter_appointment_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service_type',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_type',
            field=models.ManyToManyField(to='Appoint.servicetype'),
        ),
    ]
