# Generated by Django 4.1.3 on 2023-02-24 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appoint', '0028_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(max_length=100),
        ),
        migrations.CreateModel(
            name='AppointmentTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appoint.appointment')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appoint.timeslot')),
            ],
        ),
    ]
