# Generated by Django 4.1.3 on 2023-02-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appoint', '0029_timeslot_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time_slot',
        ),
    ]
