# Generated by Django 4.1.3 on 2023-02-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appoint', '0032_myformmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='myformmodel',
            name='form_snippet',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myformmodel',
            name='name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
