# Generated by Django 4.1.3 on 2023-02-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appoint', '0033_myformmodel_form_snippet_myformmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myformmodel',
            name='form_snippet',
        ),
    ]
