# Generated by Django 4.1.3 on 2023-02-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeupbooking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
