# Generated by Django 4.1.3 on 2023-02-24 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeupbooking', '0002_remove_payment_appointment_remove_payment_customer_and_more'),
    ]

    operations = [
    ]
